---
- hosts: localhost
  name: Deploy Cloud Pak for Security on OpenShift
  vars:
    CP4S_NAMESPACE: cp4security
    ENTITLED_REGISTRY: cp.icr.io
    ENTITLED_REGISTRY_USER: cp
    ENTITLED_REGISTRY_PWD: put-your-entitlement-key-here

  tasks:

    - name: Create cp4s namespace
      kubernetes.core.k8s:
        api_version: v1
        name: "{{ CP4S_NAMESPACE }}"
        kind: namespace
        state: present

    - name: Create pull secret
      shell: |
        oc create secret docker-registry 'ibm-entitlement-key' --docker-server={{ ENTITLED_REGISTRY }} --docker-username={{ ENTITLED_REGISTRY_USER }} --docker-password={{ ENTITLED_REGISTRY_PWD }} --namespace={{ CP4S_NAMESPACE }}
      ignore_errors: yes


    - name: Install the IBM Operator Catalog Source
      kubernetes.core.k8s:
        src: files/ibmCatalogSource.yaml
        namespace: "{{ CP4S_NAMESPACE }}"
        state: present


    - name: Wait for operator catalog source pod to be ready
      shell: |
        oc get pod -lolm.catalogSource=ibm-operator-catalog -n openshift-marketplace | grep "Running" | grep "1/1" | grep -c ""
      register: catalog_pod
      until: catalog_pod.stdout == "1"
      retries: 50
      delay: 20


    - name: Install the Cloud Pak for Security OperatorGroup
      kubernetes.core.k8s:
        src: files/operatorGroup.yaml
        namespace: "{{ CP4S_NAMESPACE }}"
        state: present


    - name: Install the Cloud Pak for Security Operator
      kubernetes.core.k8s:
        src: files/subscription.yaml
        namespace: "{{ CP4S_NAMESPACE }}"
        state: present

    - name: Wait for csv to be ready
      shell: |
        oc get csv -n {{ CP4S_NAMESPACE }} | grep "Succeeded" | grep -c ""
      register: csv_check_output
      until: csv_check_output.stdout == "2"
      retries: 100
      delay: 20


    - name: Install the Cloud Pak for Security
      kubernetes.core.k8s:
        src: files/cp4sThreatManagement.yaml
        namespace: "{{ CP4S_NAMESPACE }}"
        state: present

    

    
